// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.authors.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.util.UUID
import scala.util.Using

case class Author (
  id: UUID,
  name: String,
  bio: Option[String]
)

