// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package com.example.authors.postgresql

import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.util.UUID
import scala.util.Using

trait Queries {
  def createAuthor(
      id: UUID,
      name: String,
      bio: Option[String]): Option[Author]
  
  def deleteAuthor(id: UUID): Unit
  
  def getAuthor(id: UUID): Option[Author]
  
  def listAuthors(): List[Author]
  
}

